- hosts: localhost
  
  tasks:

  - name: update and upgrade apt packages with autoremove
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600
      autoremove: yes
