- hosts: localhost
  
  tasks:

  - name: update and upgrade apt packages with autoremove
    become: yes
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600
      autoremove: yes

  - name: install gnome shell extension dash-to-panel
    become: yes
    apt:
      name: gnome-shell-extension-dash-to-panel
      state: present

  - name: graceful restart gnome shell
    command: dbus-send --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'global.reexec_self()'
    